# HTTPS public endpoint route (TCP passthrough):
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: public-endpoint-tcp-route
  namespace: public-endpoint
spec:
  parentRefs:
    - name: primary-gateway
      namespace: gateway
      sectionName: tls-httptoolk-it
    - name: secondary-gateway
      namespace: gateway
      sectionName: tls-httptoolk-it
  rules:
    - backendRefs:
        - name: public-endpoint
          port: 4040
---
# HTTP public endpoint route:
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: public-endpoint-http-route
  namespace: public-endpoint
spec:
  parentRefs:
    - name: primary-gateway
      namespace: gateway
      sectionName: http
    - name: secondary-gateway
      namespace: gateway
      sectionName: http
  hostnames:
    - "*.e.httptoolk.it"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: public-endpoint
          port: 4040
---
# HTTPS admin endpoint route (TCP passthrough):
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: endpoint-admin-route
  namespace: public-endpoint
spec:
  parentRefs:
    - name: primary-gateway
      namespace: gateway
      sectionName: tls-endpoint-admin-httptoolkit-tech
    - name: secondary-gateway
      namespace: gateway
      sectionName: tls-endpoint-admin-httptoolkit-tech
  rules:
    - backendRefs:
        - name: public-endpoint
          port: 4000