apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: public-endpoint-route
  namespace: public-endpoint
spec:
  parentRefs:
    - name: main-gateway
      namespace: envoy-gateway-system
      sectionName: http
    - name: main-gateway
      namespace: envoy-gateway-system
      sectionName: https-httptoolk-it
  hostnames:
    - "*.e.httptoolk.it"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: public-endpoint
          port: 4040
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: endpoint-admin-route
  namespace: public-endpoint
spec:
  parentRefs:
    - name: main-gateway
      namespace: envoy-gateway-system
      sectionName: https-httptoolkit-tech
  hostnames:
    - "public-endpoint.httptoolkit.tech"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: public-endpoint
          port: 4000
      timeouts:
        request: 0s
        backendRequest: 0s